# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870f6cdb8af5a895060737d566bb11a1b959338a98ddc4e454ea64072a0b51a046aa9b4a752f439c1c9f10abda3864aab790b8deb2fc727135a9f519e1da990b

test:
  secret_key_base: 7baddbba4c962c8411d1549c8c020376b02542c6e8a44388679018d4e366ac69d886c5e52b0844a8a909af6b47d095947cfb1d37baeff56f33e7c567ddc2eb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
