source 'https://rubygems.org'

gem 'rails',          '5.0.1'
gem 'bcrypt',         '3.1.11'
gem 'puma',           '3.6.2'
gem 'sass-rails',     '~> 5.0'
gem 'uglifier',       '3.0.4'
gem 'coffee-rails',   '4.2.1'
gem 'jquery-rails'
gem 'turbolinks',     '5.0.1'
gem 'jbuilder',       '2.6.1'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'faker'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'pusher'

group :development, :test do
  gem 'sqlite3',  '1.3.13'
  gem 'byebug',   '9.0.6'
end

group :development do
  gem 'web-console',           '3.4.0'
  gem 'listen',                '3.0.8'
  gem 'spring',                '2.0.1'
  gem 'spring-watcher-listen', '2.0.1'
  gem 'mysql2',                '0.4.5'
end

group :test do
  gem 'rails-controller-testing'
  gem 'minitest-reporters'
  gem 'guard'
  gem 'guard-minitest'
end

group :production do
  gem 'pg'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
